version: '3'
services:
  python_server:
    container_name: python_server
    build: .
    ports:
      - '80:80'
    volumes:
      - ./web_app/:/var/www/web_app
      - ./apache2.conf:/etc/apache2/sites-enabled/000-default.conf
    restart: always
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
  postgres:
    container_name: postgres_db
    image: postgres:10.5
    restart: always
    environment:
      # Use the same as in the .flaskenv file.
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cars_marketplace
      - POSTGRES_PASSWORD=common
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      # Use the same as in the .flaskenv file.
      - '5532:5432'
    volumes:
      # What sql script to run when creating the container.
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  redis:
    container_name: redis_db
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6389:6379'
    # Make sure the last parameter (the pass) is the same as in the .flaskenv file.
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81