version: '3'
services:
  python_server:
    container_name: python_server
    build: .
    ports:
      - '80:80'
    volumes:
      - ./web_app/:/var/www/web_app
      - ./apache2.conf:/etc/apache2/sites-enabled/000-default.conf
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    container_name: postgres_db
    image: postgres:10.5
    restart: always
    environment:
      # Use the same as in the .flaskenv file.
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cars_marketplace
      - POSTGRES_PASSWORD=common
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      # Use the same as in the .flaskenv file.
      - '5532:5432'