version: '3'
services:
  python_server:
    env_file: '.env'
    container_name: python_server
    build: .
    ports:
      - '80:80'
    volumes:
      - ./web_app/:/var/www/web_app
      - ./apache2.conf:/etc/apache2/sites-enabled/000-default.conf
    restart: always
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
  postgres:
    env_file: '.env'
    container_name: postgres_db
    image: postgres:14.7
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "${DB_POSTGRES_PORT}:5432"
    volumes:
      # What sql script to run when creating the container.
      - ./db/create_test_db.sql:/docker-entrypoint-initdb.d/create_test_db.sql
  redis:
    env_file: '.env'
    # Source: https://geshan.com.np/blog/2022/01/redis-docker/
    container_name: redis_db
    image: redis:7.0-alpine
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    # Make sure the last parameter (the pass) is the same as in the .env file.
    # Make redis authroized with 2 different passwords (one for test).
    command: >
      sh -c "redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
      && redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD_TEST}
      "